### ISSUE TITLE
File missing in ControlsDemo project

### ISSUE THREAD

**Issue by dariospadoni** [reinforce-lab/com.ReinforceLab.MonoTouch.Controls#1]
Hi
I just downloaded your code, I noticed that MainPanel.xib (together with xib.cs and xib.designer.cs) is missing so I can't build the solution.

**Comment by khaldounaissaoui** [comment]
I have the same Problem

**Comment by tofutim** [comment]
Me three!

**Comment by reinforce-lab** [comment]
The problem of missing MainPanelxib file is fixed.
